/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Omabuarts Studio (https://sketchfab.com/omabuarts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-cat-free-b2bd1ee7858444bda366110a2d960386
Title: Toon Cat FREE
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations, Html } from "@react-three/drei";
import { gsap } from "gsap";
import { angleToRadians } from "../utils/Angle";

export function Cat() {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/cat.glb");
  const { actions } = useAnimations(animations, group);
  const [on, setOn] = useState(false);

  useEffect(() => {
    if (typeof document !== "undefined") {
      gsap.set(group.current.position, { z: -3, x: -6 });

      // Animate from right to left
      gsap
        .to(group.current.position, {
          duration: 10, // Animation duration in seconds
          z: 1, // Final position to the left side
          ease: "none",
          x: -1.5,
        })
        .then(() => {
          actions["Scene"].stop();
          setOn(true);
        });

      actions["Scene"].timeScale = 0.85;
      actions["Scene"].reset().play();
    }


  }, []);
  return (
    <group ref={group} dispose={null} rotation={[0, angleToRadians(45), 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="0df7f1c552db41979cdb0b8efba99edffbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Rig" rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_43"
                      geometry={nodes.Object_43.geometry}
                      material={materials.Mat_Gradient}
                      skeleton={nodes.Object_43.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      {on ? (
        <Html position={[0, 0.5, 0]}>
          <div className="flex items-center justify-center bg-sky-600 rounded-lg text-center text-xs p-1 font-bold">
            <p>Meow!</p>
          </div>
        </Html>
      ) : null}
    </group>
  );
}

useGLTF.preload("/cat.glb");
