/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hyungjung Kim (https://sketchfab.com/hyungjungkim)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cloud-81910476b24d4fc5a73c908d6c2a38a2
Title: Low Poly Cloud
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { gsap } from "gsap";

export function CloudOne({ x, y, z, rx, ry, rz }) {
  const { nodes, materials } = useGLTF("/cloud.glb");
  const group = useRef(null);

  useEffect(() => {
    if (typeof document !== "undefined" && group.current) {
      gsap.set(group.current.position, { x: 150 });

      gsap
        .to(group.current.position, {
          duration: 20,
          x: -200 + Math.abs(Number(x)),
          ease: "none",
        })
        .repeat(Infinity);
    }
  }, []);
  return (
    <group
      ref={group}
      dispose={null}
      scale={1.5}
      position={[x, y, z]}
      rotation={[rx, ry, rz]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/cloud.glb");
