/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: InnocentBaraka (https://sketchfab.com/InnocentBaraka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-flowers-b74c6eee48844ac395de267d373d73c1
Title: Low Poly Flowers
*/

import React, { useRef } from "react";
import { Sparkles, useGLTF } from "@react-three/drei";

export function Flowers(props) {
  const { nodes, materials } = useGLTF("/flowers.glb");
  return (
    <group {...props} dispose={null} position={[1.2, 0, 1.5]}>
      <Sparkles
        count={10}
        size={1}
        speed={0.4}
        color={"#f6e5f6"}
        position={[0.2, 0, 0]}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.609}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_4.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_5.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_6.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_7.geometry}
          material={materials["Material.005"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/flowers.glb");
