/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alan Zimmerman (https://sketchfab.com/nenjo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/birch-tree-low-poly-1d7f142738604975bbf1b03338a024dd
Title: Birch Tree - Low Poly
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Tree({ position }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/tree.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Armature|ArmatureAction"].timeScale = 1.5;
    actions["Armature|ArmatureAction"].reset().play();
  }, []);

  return (
    <group
      scale={0.003}
      ref={group}
      dispose={null}
      position={position}
      castShadow
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          castShadow
        >
          <group
            name="0531b0aee76e437286fa1480cfa5eaf0fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Armature"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={491.491}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.Tree}
                      skeleton={nodes.Object_11.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/tree.glb");
